Search.create(text: "Ender's Game")
Search.create(text: "The Catcher in the Rye")
Search.create(text: "The Girl With the Dragon Tattoo")
Search.create(text: "Ready Player One")
Search.create(text: "Earth Unaware")
Search.create(text: "Star Maker")
Search.create(text: "On Human Nature")
Search.create(text: "Satin Island")
Search.create(text: "Raptor Red")
Search.create(text: "The Social Animal")